version: '3.8'

services:
  opensearch:
    healthcheck:
      test: curl -f http://localhost:9200/_cluster/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    image: opensearchproject/opensearch:latest
    container_name: opensearch-reportsweb
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net

  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
    container_name: logstash-reportsweb
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "4560:4560"
    environment:
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
    networks:
      - opensearch-net
    depends_on:
      - opensearch

  kibana:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: kibana-reportsweb
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
    networks:
      - opensearch-net
    depends_on:
      - opensearch

networks:
  opensearch-net:
    driver: bridge