version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9201:9201"
      - "9601:9601"
    networks:
      - opensearch-net

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.1
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5001:5001"
    environment:
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
    networks:
      - opensearch-net
    depends_on:
      - opensearch

  kibana:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: kibana
    ports:
      - "5602:5602"
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
    networks:
      - opensearch-net
    depends_on:
      - opensearch

networks:
  opensearch-net:
    driver: bridge